/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dictionary;


import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * 
 * 
 * 
 * 
 *
 * @author TuanBac
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        
        initComponents();
        if(Data.nnn==1)
        {
        jPanel11.setVisible(false);
        jPanel12.setVisible(true);
        }
        else
        {
            jPanel11.setVisible(true);
             jPanel12.setVisible(false);
        }
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
          DefaultListModel model2 = new DefaultListModel();
        for(int i=Data.hist.size()-1;i>=0;i--)
        {

            model2.addElement(Data.hist.get(i));

        }
        History.setModel(model2);
         DefaultListModel model = new DefaultListModel();
        
        for(int i=0;i<Data.dict.size();i++)
        {
            model.addElement(Data.dict.get(i).word);

        }
      

        List.setModel(model);
        String x=Integer.toString(Data.nnn);
          truycap.setText(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        Help = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        TF = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        sound = new javax.swing.JButton();
        table1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList();
        show = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cb = new javax.swing.JComboBox();
        jSlider2 = new javax.swing.JSlider();
        cd2 = new javax.swing.JComboBox();
        bg2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        sp1 = new javax.swing.JButton();
        normal = new javax.swing.JButton();
        classic = new javax.swing.JButton();
        anime = new javax.swing.JButton();
        sp2 = new javax.swing.JButton();
        sp3 = new javax.swing.JButton();
        sp4 = new javax.swing.JButton();
        sp5 = new javax.swing.JButton();
        Background6 = new javax.swing.JButton();
        Background7 = new javax.swing.JButton();
        bg8 = new javax.swing.JLabel();
        table2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        TF0 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TA1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        TA2 = new javax.swing.JTextArea();
        translate = new javax.swing.JButton();
        sound2 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        exchange = new javax.swing.JButton();
        bg5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        AddWord = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        AddEx = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        Search2 = new javax.swing.JButton();
        Repair = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        rt = new javax.swing.JButton();
        bg6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Dict = new javax.swing.JLabel();
        dien = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        History = new javax.swing.JList();
        clear2 = new javax.swing.JButton();
        h = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        truycap = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary");
        setBackground(new java.awt.Color(27, 27, 27));
        setBounds(new java.awt.Rectangle(650, 400, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(550, 150));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        jPanel12.setAlignmentX(0.0F);
        jPanel12.setAlignmentY(0.0F);
        jPanel12.setName(""); // NOI18N
        jPanel12.setLayout(null);

        Help.setIcon(new javax.swing.ImageIcon("Help\\0.png")); // NOI18N
        Help.setText("jLabel9");
        Help.setAlignmentY(0.0F);
        Help.setAutoscrolls(true);
        Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                HelpMouseReleased(evt);
            }
        });
        jPanel12.add(Help);
        Help.setBounds(0, 0, 1920, 1000);

        getContentPane().add(jPanel12);
        jPanel12.setBounds(0, 0, 1920, 1000);

        jPanel11.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel11.setName(""); // NOI18N
        jPanel11.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), java.awt.Color.white)); // NOI18N
        jPanel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jPanel4.setLayout(null);

        TF.setBackground(new java.awt.Color(0, 0, 0));
        TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TF.setForeground(new java.awt.Color(255, 255, 255));
        TF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TF.setToolTipText("Tape on keyboard to transale word !!!");
        TF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TF.setCaretColor(new java.awt.Color(255, 255, 255));
        TF.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TF.setSelectionColor(new java.awt.Color(255, 153, 0));
        TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFKeyReleased(evt);
            }
        });
        jPanel4.add(TF);
        TF.setBounds(10, 20, 330, 40);

        search.setBackground(new java.awt.Color(255, 153, 0));
        search.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon("images\\search.png")); // NOI18N
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel4.add(search);
        search.setBounds(350, 20, 53, 40);

        sound.setBackground(new java.awt.Color(255, 153, 0));
        sound.setIcon(new javax.swing.ImageIcon("images\\sound.png")); // NOI18N
        sound.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundActionPerformed(evt);
            }
        });
        jPanel4.add(sound);
        sound.setBounds(410, 20, 50, 40);

        jPanel11.add(jPanel4);
        jPanel4.setBounds(30, 130, 470, 80);

        table1.setBackground(new java.awt.Color(51, 51, 51));
        table1.setForeground(new java.awt.Color(204, 102, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        List.setBackground(new java.awt.Color(0, 0, 0));
        List.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        List.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        List.setForeground(new java.awt.Color(255, 255, 255));
        List.setToolTipText("");
        List.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        List.setSelectionBackground(new java.awt.Color(255, 153, 0));
        List.setSelectionForeground(new java.awt.Color(0, 0, 0));
        List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ListMouseReleased(evt);
            }
        });
        List.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ListKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(List);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(-4, 0, 340, 670);

        show.setBackground(new java.awt.Color(255, 153, 0));
        show.setIcon(new javax.swing.ImageIcon("images\\load.png")); // NOI18N
        show.setText("Load");
        show.setBorder(null);
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel2.add(show);
        show.setBounds(350, 210, 100, 40);

        save.setBackground(new java.awt.Color(255, 153, 0));
        save.setIcon(new javax.swing.ImageIcon("images\\save.png")); // NOI18N
        save.setText("Save");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save);
        save.setBounds(350, 330, 100, 40);

        clear.setBackground(new java.awt.Color(255, 153, 0));
        clear.setIcon(new javax.swing.ImageIcon("images\\clear.png")); // NOI18N
        clear.setText("Clear");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear);
        clear.setBounds(350, 270, 100, 40);

        cb.setBackground(new java.awt.Color(27, 27, 27));
        cb.setForeground(new java.awt.Color(255, 153, 0));
        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  Anh - Việt", "  Việt - Anh", "  Việt - Việt", "  Pháp - Việt", "  Việt - Pháp" }));
        cb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        jPanel2.add(cb);
        cb.setBounds(350, 30, 100, 40);

        jSlider2.setBackground(new java.awt.Color(255, 153, 0));
        jSlider2.setMaximum(40);
        jSlider2.setValue(12);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jPanel2.add(jSlider2);
        jSlider2.setBounds(350, 150, 100, 40);

        cd2.setBackground(new java.awt.Color(27, 27, 27));
        cd2.setForeground(new java.awt.Color(255, 153, 0));
        cd2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arial", "Calibri", "Calibri Light", "Cambria", "Cambria Math", "Consolas", "Courier New", "Dialog", "DialogInput", "Leelawadee UI Semilight\t", "Monospaced", "Palatino Linotype", "SansSerif", "Segoe UI", "Segoe UI Black", "Segoe UI Light", "Segoe UI Semibold", "Segoe UI Semilight", "Serif", "Tahoma", "Times New Roman", "Verdana" }));
        cd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd2ActionPerformed(evt);
            }
        });
        jPanel2.add(cd2);
        cd2.setBounds(350, 90, 100, 40);

        bg2.setIcon(new javax.swing.ImageIcon("images\\background9.jpg")); // NOI18N
        bg2.setText("jLabel12");
        jPanel2.add(bg2);
        bg2.setBounds(-30, -240, 1920, 1000);

        table1.addTab("Suggest Word", jPanel2);

        jPanel5.setLayout(null);

        sp1.setBackground(new java.awt.Color(255, 51, 51));
        sp1.setForeground(new java.awt.Color(255, 255, 255));
        sp1.setText("Vòng xoáy");
        sp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp1ActionPerformed(evt);
            }
        });
        jPanel5.add(sp1);
        sp1.setBounds(130, 120, 200, 40);

        normal.setBackground(new java.awt.Color(255, 204, 255));
        normal.setText("Pink");
        normal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });
        jPanel5.add(normal);
        normal.setBounds(330, 50, 120, 40);

        classic.setBackground(new java.awt.Color(255, 153, 0));
        classic.setText("Classic");
        classic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        classic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classicActionPerformed(evt);
            }
        });
        jPanel5.add(classic);
        classic.setBounds(20, 50, 120, 40);

        anime.setBackground(new java.awt.Color(0, 255, 255));
        anime.setText("Blue");
        anime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animeActionPerformed(evt);
            }
        });
        jPanel5.add(anime);
        anime.setBounds(170, 50, 120, 40);

        sp2.setBackground(new java.awt.Color(0, 51, 204));
        sp2.setForeground(new java.awt.Color(255, 255, 255));
        sp2.setText("Vũ trụ diệu kì");
        sp2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp2ActionPerformed(evt);
            }
        });
        jPanel5.add(sp2);
        sp2.setBounds(130, 270, 200, 40);

        sp3.setBackground(new java.awt.Color(153, 153, 255));
        sp3.setText("Vẻ đẹp nghệ thuật");
        sp3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp3ActionPerformed(evt);
            }
        });
        jPanel5.add(sp3);
        sp3.setBounds(130, 200, 200, 40);

        sp4.setBackground(new java.awt.Color(0, 0, 0));
        sp4.setForeground(new java.awt.Color(255, 255, 255));
        sp4.setText("Black");
        sp4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp4ActionPerformed(evt);
            }
        });
        jPanel5.add(sp4);
        sp4.setBounds(130, 350, 200, 40);

        sp5.setBackground(new java.awt.Color(0, 255, 255));
        sp5.setText("Dòng chảy");
        sp5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp5ActionPerformed(evt);
            }
        });
        jPanel5.add(sp5);
        sp5.setBounds(130, 510, 200, 40);

        Background6.setBackground(new java.awt.Color(255, 153, 255));
        Background6.setText("Tâm trạng 2");
        Background6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Background6ActionPerformed(evt);
            }
        });
        jPanel5.add(Background6);
        Background6.setBounds(130, 430, 200, 40);

        Background7.setBackground(new java.awt.Color(255, 255, 204));
        Background7.setText("Art");
        Background7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Background7ActionPerformed(evt);
            }
        });
        jPanel5.add(Background7);
        Background7.setBounds(130, 590, 200, 40);

        bg8.setIcon(new javax.swing.ImageIcon("images\\background9.jpg")); // NOI18N
        bg8.setText("jLabel1");
        jPanel5.add(bg8);
        bg8.setBounds(-30, -240, 1910, 1000);

        table1.addTab("Theme", jPanel5);

        jPanel11.add(table1);
        table1.setBounds(30, 210, 470, 700);

        table2.setBackground(new java.awt.Color(51, 51, 51));
        table2.setForeground(new java.awt.Color(204, 102, 0));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setLayout(null);

        TA.setBackground(new java.awt.Color(0, 0, 0));
        TA.setColumns(20);
        TA.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TA.setForeground(new java.awt.Color(255, 153, 0));
        TA.setLineWrap(true);
        TA.setRows(5);
        TA.setWrapStyleWord(true);
        TA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TA.setDisabledTextColor(new java.awt.Color(255, 153, 0));
        TA.setEnabled(false);
        jScrollPane6.setViewportView(TA);

        jPanel7.add(jScrollPane6);
        jScrollPane6.setBounds(0, 100, 1210, 670);

        TF0.setEditable(false);
        TF0.setBackground(new java.awt.Color(0, 0, 0));
        TF0.setFont(new java.awt.Font("Arial", 3, 60)); // NOI18N
        TF0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TF0.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        TF0.setEnabled(false);
        jPanel7.add(TF0);
        TF0.setBounds(-1, 2, 1210, 100);

        table2.addTab("Explain", jPanel7);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(null);

        TA1.setColumns(20);
        TA1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TA1.setLineWrap(true);
        TA1.setRows(5);
        TA1.setWrapStyleWord(true);
        TA1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TA1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TA1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(TA1);

        jPanel8.add(jScrollPane3);
        jScrollPane3.setBounds(40, 210, 550, 242);

        TA2.setColumns(20);
        TA2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TA2.setLineWrap(true);
        TA2.setRows(5);
        TA2.setWrapStyleWord(true);
        TA2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TA2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TA2.setEnabled(false);
        jScrollPane4.setViewportView(TA2);

        jPanel8.add(jScrollPane4);
        jScrollPane4.setBounds(620, 210, 550, 242);

        translate.setBackground(new java.awt.Color(255, 153, 0));
        translate.setText("Transale");
        translate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        translate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translateActionPerformed(evt);
            }
        });
        jPanel8.add(translate);
        translate.setBounds(420, 160, 110, 39);

        sound2.setBackground(new java.awt.Color(255, 153, 0));
        sound2.setIcon(new javax.swing.ImageIcon("images\\sound.png")); // NOI18N
        sound2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sound2ActionPerformed(evt);
            }
        });
        jPanel8.add(sound2);
        sound2.setBounds(350, 160, 53, 39);

        cb1.setBackground(new java.awt.Color(27, 27, 27));
        cb1.setForeground(new java.awt.Color(255, 255, 255));
        cb1.setMaximumRowCount(15);
        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "afrikaans", "albanian", "amharic", "arabic", "armenian", "azerbaijani", "basque", "belarusian", "bengali", "bosnian", "bulgarian", "catalan", "cebuano", "chichewa", "chinese (simplified)", "chinese (traditional)", "corsican", "croatian", "czech", "danish", "dutch", "english", "esperanto", "estonian", "filipino", "finnish", "french", "frisian", "galician", "georgian", "german", "greek", "gujarati", "haitian creole", "hausa", "hawaiian", "hebrew", "hindi", "hmong", "hungarian", "icelandic", "igbo", "indonesian", "irish", "italian", "japanese", "javanese", "kannada", "kazakh", "khmer", "korean", "kurdish (kurmanji)", "kyrgyz", "lao", "latin", "latvian", "lithuanian", "luxembourgish", "macedonian", "malagasy", "malay", "malayalam", "maltese", "maori", "marathi", "mongolian", "myanmar (burmese)", "nepali", "norwegian", "pashto", "persian", "polish", "portuguese", "punjabi", "romanian", "russian", "samoan", "scots gaelic", "serbian", "sesotho", "shona", "sindhi", "sinhala", "slovak", "slovenian", "somali", "spanish", "sundanese", "swahili", "swedish", "tajik", "tamil", "telugu", "thai", "turkish", "ukrainian", "urdu", "uzbek", "vietnamese", "welsh", "xhosa", "yiddish", "yoruba", "zulu", "Filipino", "Hebrew" }));
        cb1.setSelectedIndex(98);
        cb1.setToolTipText("");
        cb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(cb1);
        cb1.setBounds(40, 160, 124, 39);

        cb2.setBackground(new java.awt.Color(27, 27, 27));
        cb2.setForeground(new java.awt.Color(255, 255, 255));
        cb2.setMaximumRowCount(15);
        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "afrikaans", "albanian", "amharic", "arabic", "armenian", "azerbaijani", "basque", "belarusian", "bengali", "bosnian", "bulgarian", "catalan", "cebuano", "chichewa", "chinese (simplified)", "chinese (traditional)", "corsican", "croatian", "czech", "danish", "dutch", "english", "esperanto", "estonian", "filipino", "finnish", "french", "frisian", "galician", "georgian", "german", "greek", "gujarati", "haitian creole", "hausa", "hawaiian", "hebrew", "hindi", "hmong", "hungarian", "icelandic", "igbo", "indonesian", "irish", "italian", "japanese", "javanese", "kannada", "kazakh", "khmer", "korean", "kurdish (kurmanji)", "kyrgyz", "lao", "latin", "latvian", "lithuanian", "luxembourgish", "macedonian", "malagasy", "malay", "malayalam", "maltese", "maori", "marathi", "mongolian", "myanmar (burmese)", "nepali", "norwegian", "pashto", "persian", "polish", "portuguese", "punjabi", "romanian", "russian", "samoan", "scots gaelic", "serbian", "sesotho", "shona", "sindhi", "sinhala", "slovak", "slovenian", "somali", "spanish", "sundanese", "swahili", "swedish", "tajik", "tamil", "telugu", "thai", "turkish", "ukrainian", "urdu", "uzbek", "vietnamese", "welsh", "xhosa", "yiddish", "yoruba", "zulu", "Filipino", "Hebrew" }));
        cb2.setSelectedIndex(21);
        cb2.setToolTipText("");
        cb2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(cb2);
        cb2.setBounds(620, 160, 114, 39);

        exchange.setBackground(new java.awt.Color(255, 153, 0));
        exchange.setIcon(new javax.swing.ImageIcon("images\\exchange.png")); // NOI18N
        exchange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangeActionPerformed(evt);
            }
        });
        jPanel8.add(exchange);
        exchange.setBounds(540, 160, 50, 40);

        bg5.setIcon(new javax.swing.ImageIcon("images\\background9.jpg")); // NOI18N
        bg5.setText("jLabel9");
        bg5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel8.add(bg5);
        bg5.setBounds(-510, -140, 1920, 1010);

        table2.addTab("Translate", jPanel8);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        AddWord.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        AddWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddWordMouseClicked(evt);
            }
        });
        AddWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AddWordKeyReleased(evt);
            }
        });
        jPanel9.add(AddWord);
        AddWord.setBounds(330, 130, 600, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Word");
        jPanel9.add(jLabel2);
        jLabel2.setBounds(230, 140, 90, 30);

        AddEx.setColumns(20);
        AddEx.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        AddEx.setLineWrap(true);
        AddEx.setRows(5);
        AddEx.setWrapStyleWord(true);
        AddEx.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        jScrollPane5.setViewportView(AddEx);

        jPanel9.add(jScrollPane5);
        jScrollPane5.setBounds(150, 200, 980, 420);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Explain");
        jPanel9.add(jLabel3);
        jLabel3.setBounds(10, 400, 120, 30);

        add.setBackground(new java.awt.Color(255, 153, 0));
        add.setIcon(new javax.swing.ImageIcon("images\\add.png")); // NOI18N
        add.setText("Add");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel9.add(add);
        add.setBounds(160, 650, 170, 50);

        Search2.setBackground(new java.awt.Color(255, 153, 0));
        Search2.setIcon(new javax.swing.ImageIcon("images\\search.png")); // NOI18N
        Search2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search2ActionPerformed(evt);
            }
        });
        jPanel9.add(Search2);
        Search2.setBounds(940, 130, 60, 50);

        Repair.setBackground(new java.awt.Color(255, 153, 0));
        Repair.setIcon(new javax.swing.ImageIcon("images\\repair.png")); // NOI18N
        Repair.setText("Repair");
        Repair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Repair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepairActionPerformed(evt);
            }
        });
        jPanel9.add(Repair);
        Repair.setBounds(710, 650, 160, 50);

        delete.setBackground(new java.awt.Color(255, 153, 0));
        delete.setIcon(new javax.swing.ImageIcon("images\\bin.png")); // NOI18N
        delete.setText("Delete");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel9.add(delete);
        delete.setBounds(440, 650, 160, 50);

        rt.setBackground(new java.awt.Color(255, 153, 0));
        rt.setIcon(new javax.swing.ImageIcon("images\\undo.png")); // NOI18N
        rt.setText("Return");
        rt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtActionPerformed(evt);
            }
        });
        jPanel9.add(rt);
        rt.setBounds(980, 650, 150, 50);

        bg6.setIcon(new javax.swing.ImageIcon("images\\background9.jpg")); // NOI18N
        bg6.setText("jLabel11");
        bg6.setAutoscrolls(true);
        jPanel9.add(bg6);
        bg6.setBounds(-510, -140, 1920, 1010);

        table2.addTab("Setting", jPanel9);

        jPanel6.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon("images\\background10.jpg")); // NOI18N
        jPanel6.add(jLabel6);
        jLabel6.setBounds(0, 0, 1207, 770);

        table2.addTab("Copyright", jPanel6);

        jPanel11.add(table2);
        table2.setBounds(510, 110, 1210, 800);

        Dict.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Dict.setForeground(new java.awt.Color(255, 255, 255));
        Dict.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dict.setText("Từ");
        jPanel11.add(Dict);
        Dict.setBounds(180, 30, 61, 48);

        dien.setIcon(new javax.swing.ImageIcon("images\\dien.png")); // NOI18N
        jPanel11.add(dien);
        dien.setBounds(250, 30, 210, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("© Team Cá Cược");
        jPanel11.add(jLabel4);
        jLabel4.setBounds(1440, 940, 230, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("23/9/2018");
        jPanel11.add(jLabel5);
        jLabel5.setBounds(1670, 950, 60, 20);

        logo.setIcon(new javax.swing.ImageIcon("images\\logo.png")); // NOI18N
        jPanel11.add(logo);
        logo.setBounds(1410, 10, 250, 100);

        History.setBackground(new java.awt.Color(0, 0, 0));
        History.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        History.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        History.setForeground(new java.awt.Color(255, 255, 255));
        History.setSelectionBackground(new java.awt.Color(255, 153, 0));
        History.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(History);

        jPanel11.add(jScrollPane2);
        jScrollPane2.setBounds(1730, 230, 180, 620);

        clear2.setBackground(new java.awt.Color(255, 153, 0));
        clear2.setIcon(new javax.swing.ImageIcon("images\\clear.png")); // NOI18N
        clear2.setText("Clear");
        clear2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear2ActionPerformed(evt);
            }
        });
        jPanel11.add(clear2);
        clear2.setBounds(1750, 860, 130, 40);

        h.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        h.setForeground(new java.awt.Color(255, 153, 0));
        h.setText("history");
        jPanel11.add(h);
        h.setBounds(1760, 160, 120, 50);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lần truy cập :");
        jPanel11.add(jLabel1);
        jLabel1.setBounds(70, 930, 180, 50);

        truycap.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        truycap.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(truycap);
        truycap.setBounds(230, 930, 110, 50);

        bg1.setIcon(new javax.swing.ImageIcon("images\\background9.jpg")); // NOI18N
        bg1.setText("jLabel6");
        jPanel11.add(bg1);
        bg1.setBounds(0, 0, 1920, 1000);

        getContentPane().add(jPanel11);
        jPanel11.setBounds(0, 0, 1920, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents
void search(String str)
{
    
         
     if(str.compareTo("")!=0)
     {
     n = Setting.Lookup(str.toLowerCase());
           String temp="";
         
           if (n == -1) {
               TA.setText("Không tìm thấy từ ! ");
            } else {
                        
                        for (int i = 0; i < Data.hist.size(); i++) {
                            if(Data.hist.get(i).equals(str)) 
                            {
                                Data.hist.remove(i);
                            
                            }
                        }
                         Data.hist.add(str);
                        
                for (int i = 0; i < Data.dict.get(n).explain.size(); i++) {
                   temp=temp+(Data.dict.get(n).explain.get(i))+"\n";
                }
                  TF0.setText(" "+Data.dict.get(n).spelling);
                 TA.setText(temp);
                  TA.setCaretPosition(0);
                   AddWord.setText(TF.getText());
            AddEx.setText(TA.getText());
             AddEx.setCaretPosition(0);
            
                }
     if(table2.getSelectedIndex()!=2)
     table2.setSelectedIndex(0);
     }
}
void history()
{
     DefaultListModel model2 = new DefaultListModel();
      for(int i=Data.hist.size()-1;i>=0;i--)
        {
           model2.addElement(Data.hist.get(i));
            
        }
     try {
            Setting.saveHis("history.txt");
        } catch (Exception ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        History.setModel(model2);
       
}
    private void TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFKeyReleased
        String word = TF.getText().toLowerCase();
        DefaultListModel model = new DefaultListModel();
        arr=Setting.Search(word);
        for(int i=0;i<arr.size();i++) model.addElement(Data.dict.get(arr.get(i)).word);
        
     
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            search(word);
            
        }
      
         else
         {
             TA.setText("");
             TF0.setText("");
         }
        history();
       List.setModel(model);

    }//GEN-LAST:event_TFKeyReleased

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
    
          String word = TF.getText();
        search(word);
        history();
    }//GEN-LAST:event_searchActionPerformed

    private void soundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundActionPerformed
      String str=TF.getText();
        listen.Speech(str);
          
    }//GEN-LAST:event_soundActionPerformed

    private void sound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sound2ActionPerformed
        String str=TA1.getText();
        listen.Speech(str);
    }//GEN-LAST:event_sound2ActionPerformed

    private void translateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translateActionPerformed
        String str=TA1.getText();
         String from=cb1.getSelectedItem().toString() ;
          String to=cb2.getSelectedItem().toString() ;
          String f="",t="";
         for(int i=0;i<Data.tran.length;i++)
         {
             if(Data.tran[i]==from)   f=Data.tran[i-1];
             if(Data.tran[i]==to)     t=Data.tran[i-1];
         }
                if(str.equals("")==false)
                {
            String temp=Setting.translate(str,f,t);
             TA2.setText(temp);
                }
                else  JOptionPane.showMessageDialog(null, "Hãy gõ đoạn văn !");
        
            
    }//GEN-LAST:event_translateActionPerformed

    private void clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear2ActionPerformed
            Setting.clear2();
           
             history();
    }//GEN-LAST:event_clear2ActionPerformed
void search2(String str)
{
           int x = Setting.Lookup(str);
           String temp="";
            if (x == -1) {
                      AddEx.setEnabled(false);
               AddEx.setText("Không tìm thấy từ ! ");
               
            } else {
                 AddEx.setEnabled(true);
                for (int i = 0; i < Data.dict.get(x).explain.size(); i++) {
                   temp=temp+(Data.dict.get(x).explain.get(i))+"\n";
                }
               
                 AddEx.setText(temp);
                  AddEx.setCaretPosition(0);
            
                }
            
}
    private void exchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangeActionPerformed
         int from=cb1.getSelectedIndex() ;
          int to=cb2.getSelectedIndex() ;
        cb1.setSelectedIndex(to);
        cb2.setSelectedIndex(from);
        TA1.setText(TA2.getText());
        TA2.setText("");
    }//GEN-LAST:event_exchangeActionPerformed

    private void HelpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseReleased
            if(Data.nnn==1)
       {
        ss++;
   
       
        if(ss==1)
        {
             jPanel11.setVisible(true);
             jPanel12.setVisible(false);
        }
       }
    
    }//GEN-LAST:event_HelpMouseReleased

    private void TA1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TA1KeyReleased
 
         TA2.setText("");
              // TODO add your handling code here:
    }//GEN-LAST:event_TA1KeyReleased

    private void Search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search2ActionPerformed
       
        String word = AddWord.getText();
        if(word.compareTo("")!=0)
        {
        search2(word);
         TA.setCaretPosition(0);
        }
    }//GEN-LAST:event_Search2ActionPerformed

    private void RepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepairActionPerformed
             String word = AddWord.getText();
            String s = AddEx.getText();
               if(word.compareTo("")!=0)
               {
        if(s.compareTo("")!=0)
        {
        int n = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa không ?" ,"Thông báo",JOptionPane.YES_NO_OPTION);
            
        if(n == JOptionPane.YES_OPTION)
        if(Setting.repair(AddWord.getText(),AddEx.getText())==-1)
        {
            JOptionPane.showMessageDialog(null, "Từ @ nên để trong dấu ''. Ví dụ @a hoặc @'a'");
            
        }
        
        }
        else JOptionPane.showMessageDialog(null, "Bạn chưa nhập nghĩa !!!");
               }
    }//GEN-LAST:event_RepairActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String str=AddWord.getText();
        if(str.compareTo("")!=0)
        {
        int n = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không ?" ,"Thông báo",JOptionPane.YES_NO_OPTION);
            
        if(n == JOptionPane.YES_OPTION)
        {
        
        int nnnnn=Setting.Lookup(str.toLowerCase());
        if(nnnnn!=-1){
        Setting.delete(nnnnn);
        DefaultListModel model = new DefaultListModel();
    

        for(int i=0;i<Data.dict.size();i++)
        {
            model.addElement(Data.dict.get(i).word);

        }
        AddWord.setText("");
        AddEx.setText("");
        List.setModel(model);
        }
        
            
        }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if(AddEx.getText().compareTo("")!=0)
        {
        String w=AddWord.getText();
           String word = AddWord.getText();
        if(w.compareTo("")!=0)
        {
        String e=AddEx.getText();
        
        int m=Setting.Lookup(w.toLowerCase());
        if(m==-1)
        {
            if(Setting.add(w, e)==-1) JOptionPane.showMessageDialog(null, "Từ @ nên để trong dấu ''. Ví dụ '@' hoặc '@a' ");
              else
              {
                   // Setting.QuickSort(0, Data.dict.size()-1);
                    DefaultListModel model = new DefaultListModel();
    

        for(int i=0;i<Data.dict.size();i++)
        {
            model.addElement(Data.dict.get(i).word);

        }
        List.setModel(model);
                         
                }
        }
        else JOptionPane.showMessageDialog(null, "Từ này có rồi !!!");
        }
        }
        else JOptionPane.showMessageDialog(null, "Bạn chưa nhập nghĩa !!!");
    }//GEN-LAST:event_addActionPerformed

    private void AddWordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddWordKeyReleased
         AddEx.setEnabled(true);
        AddEx.setText("");
    }//GEN-LAST:event_AddWordKeyReleased

    private void Background7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Background7ActionPerformed
        bg1.setIcon(new javax.swing.ImageIcon("images\\7.gif"));
        bg2.setIcon(new javax.swing.ImageIcon("images\\7.gif"));
      
        bg5.setIcon(new javax.swing.ImageIcon("images\\7.gif"));
        bg6.setIcon(new javax.swing.ImageIcon("images\\7.gif"));
        bg8.setIcon(new javax.swing.ImageIcon("images\\7.gif"));

    }//GEN-LAST:event_Background7ActionPerformed

    private void Background6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Background6ActionPerformed
        bg1.setIcon(new javax.swing.ImageIcon("images\\6.gif"));
        bg2.setIcon(new javax.swing.ImageIcon("images\\6.gif"));
       
        bg5.setIcon(new javax.swing.ImageIcon("images\\6.gif"));
        bg6.setIcon(new javax.swing.ImageIcon("images\\6.gif"));
        bg8.setIcon(new javax.swing.ImageIcon("images\\6.gif"));

    }//GEN-LAST:event_Background6ActionPerformed

    private void sp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp5ActionPerformed
        bg1.setIcon(new javax.swing.ImageIcon("images\\5.gif"));
        bg2.setIcon(new javax.swing.ImageIcon("images\\5.gif"));
       
        bg5.setIcon(new javax.swing.ImageIcon("images\\5.gif"));
        bg6.setIcon(new javax.swing.ImageIcon("images\\5.gif"));
        bg8.setIcon(new javax.swing.ImageIcon("images\\5.gif"));

    }//GEN-LAST:event_sp5ActionPerformed

    private void sp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp4ActionPerformed
        bg1.setIcon(new javax.swing.ImageIcon("images\\4.gif"));
        bg2.setIcon(new javax.swing.ImageIcon("images\\4.gif"));
       
        bg5.setIcon(new javax.swing.ImageIcon("images\\4.gif"));
        bg6.setIcon(new javax.swing.ImageIcon("images\\4.gif"));
        bg8.setIcon(new javax.swing.ImageIcon("images\\4.gif"));

    }//GEN-LAST:event_sp4ActionPerformed

    private void sp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp3ActionPerformed
        bg1.setIcon(new javax.swing.ImageIcon("images\\3.gif"));
        bg2.setIcon(new javax.swing.ImageIcon("images\\3.gif"));
     
        bg5.setIcon(new javax.swing.ImageIcon("images\\3.gif"));
        bg6.setIcon(new javax.swing.ImageIcon("images\\3.gif"));
        bg8.setIcon(new javax.swing.ImageIcon("images\\3.gif"));

    }//GEN-LAST:event_sp3ActionPerformed

    private void sp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp2ActionPerformed
        bg1.setIcon(new javax.swing.ImageIcon("images\\2.gif"));
        bg2.setIcon(new javax.swing.ImageIcon("images\\2.gif"));
      
        bg5.setIcon(new javax.swing.ImageIcon("images\\2.gif"));
        bg6.setIcon(new javax.swing.ImageIcon("images\\2.gif"));
        bg8.setIcon(new javax.swing.ImageIcon("images\\2.gif"));

    }//GEN-LAST:event_sp2ActionPerformed

    private void animeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animeActionPerformed
           TF.setSelectedTextColor(new java.awt.Color(0,0,0));
             TF.setSelectionColor(new java.awt.Color(0, 255, 255));
               TA1.setSelectionColor(new java.awt.Color(0, 255, 255));
               AddEx.setSelectionColor(new java.awt.Color(0, 255, 255));
               AddWord.setSelectionColor(new java.awt.Color(0, 255, 255));
        bg1.setIcon(new javax.swing.ImageIcon("images\\Anime.png"));
        bg2.setIcon(new javax.swing.ImageIcon("images\\Anime.png"));
        bg5.setIcon(new javax.swing.ImageIcon("images\\Anime.png"));
        bg6.setIcon(new javax.swing.ImageIcon("images\\Anime.png"));
        bg8.setIcon(new javax.swing.ImageIcon("images\\Anime.png"));

        logo.setIcon(new javax.swing.ImageIcon("images\\logo2.png"));
        search.setBackground(new java.awt.Color(0, 255, 255));
        sound.setBackground(new java.awt.Color(0, 255, 255));
        show.setBackground(new java.awt.Color(0, 255, 255));

        save.setBackground(new java.awt.Color(0, 255, 255));
        exchange.setBackground(new java.awt.Color(0, 255, 255));
        add.setBackground(new java.awt.Color(0, 255, 255));
        delete.setBackground(new java.awt.Color(0, 255, 255));
        
        clear.setBackground(new java.awt.Color(0, 255, 255));
        
        History.setSelectionBackground(new java.awt.Color(0, 255, 255));
        clear2.setBackground(new java.awt.Color(0, 255, 255));
        translate.setBackground(new java.awt.Color(0, 255, 255));
        sound2.setBackground(new java.awt.Color(0, 255, 255));
        
          table1.setForeground(new java.awt.Color(0,153,153));
        table2.setForeground(new java.awt.Color(0,153,153));
         table1.setBackground(Color.WHITE);
        table2.setBackground(Color.WHITE);
        
        Search2.setBackground(new java.awt.Color(0, 255, 255));
        Repair.setBackground(new java.awt.Color(0, 255, 255));

        TA.setDisabledTextColor(new java.awt.Color(0, 255, 255));
        dien.setIcon(new javax.swing.ImageIcon("images\\dien2.png"));
        List.setSelectionBackground(new java.awt.Color(0, 255, 255));
         h.setForeground(new java.awt.Color(0, 255, 255));
            jPanel4.setBackground(Color.BLACK);
            jSlider2.setBackground(new java.awt.Color(0, 255, 255));
             TF0.setBackground(Color.BLACK);
             TA.setBackground(Color.BLACK);
              TF.setForeground(Color.BLACK);
             TF.setBackground(Color.WHITE);
             List.setBackground(Color.BLACK);
             History.setBackground(Color.BLACK);
             List.setForeground(new java.awt.Color(0, 255, 255));
             History.setForeground(new java.awt.Color(0, 255, 255));
               cd2.setBackground(Color.WHITE);
             cd2.setForeground(new java.awt.Color(0, 102, 102));
             cb.setBackground(Color.WHITE);
             cb.setForeground(new java.awt.Color(0, 102, 102));
              cb1.setBackground(Color.WHITE);
             cb1.setForeground(new java.awt.Color(0, 102, 102));
              cb2.setBackground(Color.WHITE);
             cb2.setForeground(new java.awt.Color(0, 102, 102));
             rt.setBackground(new java.awt.Color(0, 255, 255));
    }//GEN-LAST:event_animeActionPerformed

    private void classicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classicActionPerformed
        bg1.setIcon(new javax.swing.ImageIcon("images\\background9.jpg"));
        bg2.setIcon(new javax.swing.ImageIcon("images\\background9.jpg"));
        bg5.setIcon(new javax.swing.ImageIcon("images\\background9.jpg"));
        bg6.setIcon(new javax.swing.ImageIcon("images\\background9.jpg"));
        bg8.setIcon(new javax.swing.ImageIcon("images\\background9.jpg"));
        
        logo.setIcon(new javax.swing.ImageIcon("images\\logo.png"));
        search.setBackground(new java.awt.Color(255,153,0));
        sound.setBackground(new java.awt.Color(255,153,0));
        show.setBackground(new java.awt.Color(255,153,0));
jSlider2.setBackground(new java.awt.Color(255,153,0));
        save.setBackground(new java.awt.Color(255,153,0));
        exchange.setBackground(new java.awt.Color(255,153,0));
        add.setBackground(new java.awt.Color(255,153,0));
        delete.setBackground(new java.awt.Color(255,153,0));
        
        clear.setBackground(new java.awt.Color(255,153,0));
        
        History.setSelectionBackground(new java.awt.Color(255,153,0));
        clear2.setBackground(new java.awt.Color(255,153,0));
        translate.setBackground(new java.awt.Color(255,153,0));
        sound2.setBackground(new java.awt.Color(255,153,0));
        
          table1.setForeground(new java.awt.Color(204,102,0));
        table2.setForeground(new java.awt.Color(204,102,0));
         table1.setBackground(new java.awt.Color(   51,51,51));
        table2.setBackground(new java.awt.Color(   51,51,51));
   
        Search2.setBackground(new java.awt.Color(255,153,0));
        Repair.setBackground(new java.awt.Color(255,153,0));

        TA.setDisabledTextColor(new java.awt.Color(255,153,0));
        dien.setIcon(new javax.swing.ImageIcon("images\\dien.png"));
        List.setSelectionBackground(new java.awt.Color(255,153,0));
        
            jPanel4.setBackground(Color.BLACK);
         
             TF0.setBackground(Color.BLACK);
             TA.setBackground(Color.BLACK);
              TF.setForeground(Color.WHITE);
             TF.setBackground(Color.BLACK);
             List.setBackground(Color.BLACK);
             History.setBackground(Color.BLACK);
             List.setForeground(Color.WHITE);
             History.setForeground(Color.WHITE);
            h.setForeground(new java.awt.Color(255,153,0));
             cb.setBackground(new java.awt.Color( 27,27,27));
             cb.setForeground(new java.awt.Color(255,153,0));
              cb1.setBackground(new java.awt.Color( 27,27,27));
             cb1.setForeground(new java.awt.Color(255,153,0));
              cb2.setBackground(new java.awt.Color( 27,27,27));
             cb2.setForeground(new java.awt.Color(255,153,0));
             rt.setBackground(new java.awt.Color(255,153,0));
              cd2.setBackground(new java.awt.Color( 27,27,27));
             cd2.setForeground(new java.awt.Color(255,153,0));
             TF.setSelectedTextColor(new java.awt.Color(0,0,0));
             TF.setSelectionColor(new java.awt.Color(255,153,0));
               TA1.setSelectionColor(new java.awt.Color(255,153,0));
               AddEx.setSelectionColor(new java.awt.Color(255,153,0));
               AddWord.setSelectionColor(new java.awt.Color(255,153,0));
    }//GEN-LAST:event_classicActionPerformed

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
          TF.setSelectedTextColor(new java.awt.Color(0,0,0));
             TF.setSelectionColor(new java.awt.Color(255,204,255));
           TA1.setSelectionColor(new java.awt.Color(255,204,255));
               AddEx.setSelectionColor(new java.awt.Color(255,204,255));
               AddWord.setSelectionColor(new java.awt.Color(255,204,255));
        bg1.setIcon(new javax.swing.ImageIcon("images\\background7.png"));
        bg2.setIcon(new javax.swing.ImageIcon("images\\background8.png"));
    
        bg5.setIcon(new javax.swing.ImageIcon("images\\background8.png"));
        bg6.setIcon(new javax.swing.ImageIcon("images\\background8.png"));
        bg8.setIcon(new javax.swing.ImageIcon("images\\background8.png"));
           
        search.setBackground(new java.awt.Color(255,204,255));
        sound.setBackground(new java.awt.Color(255,204,255));
        show.setBackground(new java.awt.Color(255,204,255));
        jSlider2.setBackground(new java.awt.Color(255,204,255));
        save.setBackground(new java.awt.Color(255,204,255));
        logo.setIcon(new javax.swing.ImageIcon("images\\logo3.png"));
        add.setBackground(new java.awt.Color(255,204,255));
        delete.setBackground(new java.awt.Color(255,204,255));
        clear.setBackground(new java.awt.Color(255,204,255));
        clear2.setBackground(new java.awt.Color(255,204,255));
        translate.setBackground(new java.awt.Color(255,204,255));
       sound2.setBackground(new java.awt.Color(255,204,255));
       
        table1.setForeground(new java.awt.Color(153,102,153));
        table2.setForeground(new java.awt.Color(153,102,153));
         table1.setBackground(Color.WHITE);
        table2.setBackground(Color.WHITE);
        
        TF.setBackground(Color.WHITE);
        TF.setForeground(Color.BLACK);
        Search2.setBackground(new java.awt.Color(255,204,255));
        Repair.setBackground(new java.awt.Color(255,204,255));
        exchange.setBackground(new java.awt.Color(255,204,255));
        dien.setIcon(new javax.swing.ImageIcon("images\\dien4.png")); // NOI18N
        
        TA.setDisabledTextColor(Color.BLACK);
        List.setSelectionBackground(new java.awt.Color(255,204,255));
        List.setBackground(Color.WHITE);
        List.setForeground(Color.BLACK);
        TA.setBackground(Color.WHITE);
        History.setBackground(Color.WHITE);
        History.setSelectionBackground(new java.awt.Color(255,204,255));
        History.setForeground(Color.BLACK);
        h.setForeground(new java.awt.Color(255,0,255));
        jPanel4.setBackground(new java.awt.Color(153,102,153));
        TF0.setBackground(new java.awt.Color(153,102,153));
        cb.setBackground(Color.WHITE);
        cb.setForeground(new java.awt.Color(153,102,153));
        cb1.setBackground(Color.WHITE);
        cb1.setForeground(new java.awt.Color(153,102,153));
        cb2.setBackground(Color.WHITE);
        cb2.setForeground(new java.awt.Color(153,102,153));
          rt.setBackground(new java.awt.Color(255,204,255));
          
        cd2.setBackground(Color.WHITE);
        cd2.setForeground(new java.awt.Color(153,102,153));
          
    }//GEN-LAST:event_normalActionPerformed

    private void sp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp1ActionPerformed

        bg1.setIcon(new javax.swing.ImageIcon("images\\1.gif"));
      
     
        bg5.setIcon(new javax.swing.ImageIcon("images\\1.gif"));
        bg6.setIcon(new javax.swing.ImageIcon("images\\1.gif"));
        bg8.setIcon(new javax.swing.ImageIcon("images\\1.gif"));

    }//GEN-LAST:event_sp1ActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        Setting.clear();
        TA.setText("");
        List.setModel(new DefaultListModel());
        TF.setText("");
        String d=cb.getSelectedItem().toString();
        try {
            if(d.equals("  Anh - Việt"))
            {
                Setting.getData("dictionaries.txt");
            }
            else  if(d.equals("  Việt - Anh"))
            {
                Setting.getData("dictionaries2.txt");
            }
            else if(d.equals("  Việt - Pháp"))
            {
                Setting.getData("dictionaries3.txt");
            }
            else
            if(d.equals("  Pháp - Việt"))
            {
                Setting.getData("dictionaries4.txt");
            }
            else  if(d.equals("  Việt - Việt"))
            {
                Setting.getData("dictionaries5.txt");
            }
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
          DefaultListModel model = new DefaultListModel();
        String temp="";
  
        for(int i=0;i<Data.dict.size();i++)
        {
            model.addElement(Data.dict.get(i).word);

        }
        TA.setText("");
        TF0.setText("");
        TF.setText("");
        Data.temp.clear();
         Data.temp3.clear();
        List.setModel(model);
        
    }//GEN-LAST:event_cbActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa toàn bộ dữ liệu không ?" ,"Thông báo",JOptionPane.YES_NO_OPTION);

        if(n == JOptionPane.YES_OPTION)
        {
            Setting.clear();
            TA.setText("");
            List.setModel(new DefaultListModel());
            TF.setText("");
            TF0.setText("");
        }
    }//GEN-LAST:event_clearActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String d=cb.getSelectedItem().toString();
        try {
              if(d.equals("  Anh - Việt"))
            {
               
                 Setting.saveData("dictionaries.txt");
            }
            else  if(d.equals("  Việt - Anh"))
            {
                Setting.saveData("dictionaries2.txt");
            }
            else if(d.equals("  Việt - Pháp"))
            {
                Setting.saveData("dictionaries3.txt");
            }
            else
            if(d.equals("  Pháp - Việt"))
            {
                 Setting.saveData("dictionaries4.txt");
            }
            else  if(d.equals("  Việt - Việt"))
            {
                Setting.saveData("dictionaries5.txt");
            }
        } catch (Exception ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
             //Setting.xoa();
        DefaultListModel model = new DefaultListModel();
        String temp="";
  
        for(int i=0;i<Data.dict.size();i++)
        {
            model.addElement(Data.dict.get(i).word);

        }
        TA.setText("");
        TF0.setText("");
        TF.setText("");

        List.setModel(model);
        
    }//GEN-LAST:event_showActionPerformed

    private void rtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtActionPerformed
        Setting.undo();
           DefaultListModel model = new DefaultListModel();
    

        for(int i=0;i<Data.dict.size();i++)
        {
            model.addElement(Data.dict.get(i).word);

        }
        List.setModel(model);
    }//GEN-LAST:event_rtActionPerformed

    private void AddWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddWordMouseClicked
         AddEx.setEnabled(true);
               AddEx.setText("");
    }//GEN-LAST:event_AddWordMouseClicked

    private void ListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListMouseReleased
          if(List.getModel().getSize()!=0)
        {
            String selected = List.getSelectedValue().toString();
            TF.setText(selected);
           
            search(selected);
          
            history();
        }
    }//GEN-LAST:event_ListMouseReleased

    private void ListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ListKeyReleased
          if(List.getModel().getSize()!=0)
        {
            String selected = List.getSelectedValue().toString();
            TF.setText(selected);
            search(selected);
            
            history();
        }
    }//GEN-LAST:event_ListKeyReleased

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        int n=jSlider2.getValue();
         String d=cd2.getSelectedItem().toString();
         
        TA.setFont(new java.awt.Font(d, 1, n+12)); // NOI18N
    }//GEN-LAST:event_jSlider2StateChanged

    private void cd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd2ActionPerformed
             String d=cd2.getSelectedItem().toString();
                int n=jSlider2.getValue();
                
              TA.setFont(new java.awt.Font(d,1,n+12));
              List.setFont(new java.awt.Font(d,1,18));
              TF.setFont(new java.awt.Font(d,1,24));
                      TF0.setFont(new java.awt.Font(d,3,60));
                      History.setFont(new java.awt.Font(d,1,18));
                      AddWord.setFont(new java.awt.Font(d,1,24));
                       AddEx.setFont(new java.awt.Font(d,0,24));
                     
    }//GEN-LAST:event_cd2ActionPerformed

    
     public ArrayList<Integer> arr;
     public int n = 0;
     public int ss=0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddEx;
    private javax.swing.JTextField AddWord;
    private javax.swing.JButton Background6;
    private javax.swing.JButton Background7;
    private javax.swing.JLabel Dict;
    private javax.swing.JLabel Help;
    private javax.swing.JList History;
    private javax.swing.JList List;
    private javax.swing.JButton Repair;
    private javax.swing.JButton Search2;
    private javax.swing.JTextArea TA;
    private javax.swing.JTextArea TA1;
    private javax.swing.JTextArea TA2;
    private javax.swing.JTextField TF;
    private javax.swing.JTextField TF0;
    private javax.swing.JButton add;
    private javax.swing.JButton anime;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg5;
    private javax.swing.JLabel bg6;
    private javax.swing.JLabel bg8;
    private javax.swing.JComboBox cb;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cd2;
    private javax.swing.JButton classic;
    private javax.swing.JButton clear;
    private javax.swing.JButton clear2;
    private javax.swing.JButton delete;
    private javax.swing.JLabel dien;
    private javax.swing.JButton exchange;
    private javax.swing.JLabel h;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JLabel logo;
    private javax.swing.JButton normal;
    private javax.swing.JButton rt;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JButton show;
    private javax.swing.JButton sound;
    private javax.swing.JButton sound2;
    private javax.swing.JButton sp1;
    private javax.swing.JButton sp2;
    private javax.swing.JButton sp3;
    private javax.swing.JButton sp4;
    private javax.swing.JButton sp5;
    private javax.swing.JTabbedPane table1;
    private javax.swing.JTabbedPane table2;
    private javax.swing.JButton translate;
    private javax.swing.JLabel truycap;
    // End of variables declaration//GEN-END:variables
}
